version: '3.9'
services:
  store-es-db:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.9.0'
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=true
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - './store-es-db-data:/usr/share/elasticsearch/data'
    ports:
      - '9201:9200'
    networks:
      - domesticberries
    healthcheck:
      interval: 20s
      retries: 10
      test: >-
        curl -s http://localhost:9201/_cluster/health | grep -vq
        '"status":"red"'
    restart: unless-stopped
networks:
  domesticberries:
    name: domesticberries
    external: true
